export const theme = {
    colors: {
        primary: "#D4AF37",
        secondary: "#000000",
        accent: "#FFFFFF",
        background: {
            dark: "#0A0A0A",
            darker: "#000000",
            light: "#F5F5F5",
        },
        text: {
            primary: "#FFFFFF",
            secondary: "#AAAAAA",
            gold: "#D4AF37", 
            dark: "#333333",
        },
        success: "#4CAF50",
        error: "#F44336",
        warning: "#FF9800",
    },
    spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        xxl: "3rem",
    },
    typography: {
        fontFamily: {
            primary: "'Montserrat', sans-serif",
            secondary: "'Space Mono', monospace",
        },
        fontSize: {
            xs: "0.75rem",
            sm: "0.875rem",
            md: "1rem",
            lg: "1.25rem",
            xl: "1.5rem",
            xxl: "2rem",
            xxxl: "3rem",
            huge: "5rem",
        },
        fontWeight: {
            regular: 400,
            medium: 500,
            semibold: 600,
            bold: 700,
        },
        letterSpacing: {
            tight: "-0.05em",
            normal: "0",
            wide: "0.05em",
            wider: "0.1em",
            widest: "0.2em",
        },
    },
    borderRadius: {
        sm: "0.25rem",
        md: "0.5rem",
        lg: "1rem",
        full: "9999px",
    },
    shadows: {
        sm: "0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)",
        md: "0 4px 6px rgba(0, 0, 0, 0.1)",
        lg: "0 10px 15px rgba(0, 0, 0, 0.1)",
        gold: "0 0 10px rgba(212, 175, 55, 0.5)",
    },
    transitions: {
        fast: "0.15s ease",
        normal: "0.3s ease",
        slow: "0.5s ease",
    },
    breakpoints: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
    },
};